version: '3'
services:
  app:
    image: flask_server
    container_name: gj_demoPage
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - "13000:15000"
  thermal_model:
    image: detection_server
    container_name: gj_triton
    build:
      context: triton
      dockerfile: Dockerfile
    ports:
      - "13100-13102:8000-8002"
    command:
      - tritonserver
      # - --gpus 0
      - --model-repository=/models
      - --backend-config=tensorflow,version=2
      - --strict-model-config=false
      - --log-verbose=1
